pipeline{
   agent {
  label 'devServer'
}

parameters {
  string defaultValue: 'smith', name: 'LASTNAME'
}

environment{
    NAME = "John Doe"
}

tools {

    maven 'mymaven'
}

        stages{

            stage('build'){

                steps{
                    
                    sh 'mvn clean package'
                    echo "hello $NAME ${params.LASTNAME}"
                }
                post {
      success {
       archiveArtifacts artifacts: '**/target/*.jar'
         }
           }
            }

           
        }
    
}


/* pipeline {
    agent {
        docker {
            image 'maven:3.9.0'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
} */
